### ISSUE TITLE
【建议】：可以直接通过使用chatgpt token 登录

### ISSUE THREAD

**Issue by alex-oos** [moyangzhan/langchain4j-aideepin#1]
建议，取消注册，登录按钮，并且将服务修改的轻量一些，使用本地内存数据库，那样子，开源出来，估计会有更多的人star的

**Comment by moyangzhan** [comment]
那直接用chatgpt-web就可以了，URL：https://github.com/Chanzhaoyu/chatgpt-web

**Comment by alex-oos** [comment]
嗯呢
