### ISSUE TITLE
实际后端口在哪里设置，该如何与前端配置文件.env中的端口对应

### ISSUE THREAD

**Issue by SakuraAug** [moyangzhan/langchain4j-aideepin#10]

**Comment by moyangzhan** [comment]
后端服务端口默认为9999，配置在：adi-bootstrap\src\main\resources\application.yml的server.port

如果改了后端服务的端口，则前端需要改两处：
1. .env文件中的VITE_APP_API_BASE_URL对应的端口（开发环境）
2. nginx配置中后端服务的端口（生产环境）
nginx配置可参考：https://github.com/moyangzhan/langchain4j-aideepin-web/blob/main/docker-compose/nginx/nginx.conf
将proxy_pass http://localhost:9999/;中的9999改成你设置的端口
