### ISSUE TITLE
后端代码启动时的问题

### ISSUE THREAD

**Issue by SakuraAug** [moyangzhan/langchain4j-aideepin#11]
cd adi-bootstrap/target
该目录下没有adi-chat-0.0.1-SNAPSHOT.jar 文件，
nohup java -jar -Xms768m -Xmx1024m -XX:+HeapDumpOnOutOfMemoryError adi-chat-0.0.1-SNAPSHOT.jar --spring.profiles.active=[dev|prod] dev/null 2>&1 &
在adi-chat/target目录下执行上述命令控制台会返回“adi-chat-0.0.1-SNAPSHOT.jar中没有主清单属性”，且用readme的docker启动方法，在docker desktop下建立的容器也不能运行，显示“no main manifest attribute”，该如何解决？

**Comment by moyangzhan** [comment]
不好意思，readme里写错了，adi-bootstrap/target里只有adi-bootstrap-0.0.1-SNAPSHOT.jar，没有adi-chat相关的jar包，启动adi-bootstrap-0.0.1-SNAPSHOT.jar就行了
