### ISSUE TITLE
仍旧是激活邮件发送问题

### ISSUE THREAD

**Issue by SakuraAug** [moyangzhan/langchain4j-aideepin#12]
重新改了一下有些配置..为什么在本地运行时注册激活邮件发到了作者的体验网站这里？一直显示激活码失效。
![image](https://github.com/moyangzhan/langchain4j-aideepin/assets/128482439/a7d66045-fce5-4452-b3f4-f25bcc2fdf45)
![~MZ }W NVWUT (D2GQH }HL](https://github.com/moyangzhan/langchain4j-aideepin/assets/128482439/f21da63e-399c-426c-a5d6-996bb916456f)

配置文件所有端口都没改过，只填了邮件，数据库等配置，前端项目是按照readme给的docker启动的，命令一致。因为是win系统，后端项目是打包后直接启动的adi-bootstrap-0.0.1-SNAPSHOT.jar

**Comment by moyangzhan** [comment]
需要在这里把激活跳转地址改掉：adi-bootstrap\src\main\resources\application.yml
将adi.frontend-url和adi.backend-url改成你的域名就可以了

**Comment by SakuraAug** [comment]
所以我是否需要新建立一个网站？还是用ip地址加端口的形式？

**Comment by SakuraAug** [comment]
如果换成域名的话，还需要配置DNS，设置服务器之类的吧？不可以在本地运行吗？

**Comment by moyangzhan** [comment]
如果是生产环境就换成域名，开发环境的话应该不会做调整，只是需要你在idea里指定profile为dev，让程序自动用application-dev.yml的配置就行了，默认是 http://localhost:1002/
