### ISSUE TITLE
知识库上传文件始终失败

### ISSUE THREAD

**Issue by SakuraAug** [moyangzhan/langchain4j-aideepin#13]
在本地尝试了好几遍，还是不能上传txt，pdf一类的文档，但是聊天功能正常。在作者的体验网址上可以正常上传文档，这是什么原因？是不是代码没有更新？
![6324380de3eb4fa593c0ca0b35af677](https://github.com/moyangzhan/langchain4j-aideepin/assets/128482439/68e64b79-0b3e-4e81-bf84-95a47e8e6f82)

![e118fa7543e41f7e1eb0a6c8b3f8ec3](https://github.com/moyangzhan/langchain4j-aideepin/assets/128482439/b4d2a7b5-e998-4ec2-ac80-618c409c303c)

**Comment by SakuraAug** [comment]
![e118fa7543e41f7e1eb0a6c8b3f8ec3](https://github.com/moyangzhan/langchain4j-aideepin/assets/128482439/32b6e8d2-43ad-411f-b4cb-cb8a29297f13)

**Comment by moyangzhan** [comment]
最好是把完整的错误堆栈贴上来

然后有没有可能是因为以下几个目录没有写入权限？
local:
  files: /data/files/
  images: /data/images/
  tmp_images: /data/tmp_images/

**Comment by SakuraAug** [comment]
已解决
