### ISSUE TITLE
功能优化

### ISSUE THREAD

**Issue by Strong-Gavin** [moyangzhan/langchain4j-aideepin#14]
知识库问答是否考虑增加原文引用，类似FastGPT中相关内容

**Comment by moyangzhan** [comment]
有的，这个会慢慢加上去，界面显示效果就是类似AI搜索那样，在答案下面出现引用列表，然后打算做成可配置的，每个知识库的管理员决定是否要显示该项

**Comment by Strong-Gavin** [comment]
目前在演示环境测试了测试，部分列表新增后页面不刷新，需要重新刷新页面。另外目前我看前端是否考虑更换为elemenui框架

**Comment by moyangzhan** [comment]
> 目前在演示环境测试了测试，部分列表新增后页面不刷新，需要重新刷新页面。另外目前我看前端是否考虑更换为elemenui框架

1. 可以列出不刷新的列表
2. 目前没有更新ui框架的打算
