### ISSUE TITLE
Could not load font file: C:\WINDOWS\FONTS\mstmc.ttf

### ISSUE THREAD

**Issue by hongwazi** [moyangzhan/langchain4j-aideepin#16]
org.apache.pdfbox.pdmodel.font.FileSystemFontProvider Could not load font file: C:\WINDOWS\FONTS\mstmc.ttf，知识库解析找不到ttf文件，window10环境

**Comment by moyangzhan** [comment]
删除这个文件试试~~ 删除之前记得先备份，具体看这里：https://github.com/US-CBP/GTAS/issues/1723
