### ISSUE TITLE
项目在windows下用idea加载会直接闪退

### ISSUE THREAD

**Issue by jscksy** [moyangzhan/langchain4j-aideepin#17]
这个项目需要在linux下开发吗？

**Comment by moyangzhan** [comment]
不需要的，一直是以windows下开发，是在哪个过程闪退？导入项目时？

**Comment by jscksy** [comment]
> 不需要的，一直是在windows下开发，是在哪个过程闪退？导入项目时？

是的，应该是我这边环境的问题
