### ISSUE TITLE
window7环境启动报onnxruntime.dll can not find

### ISSUE THREAD

**Issue by beyond-zj** [moyangzhan/langchain4j-aideepin#18]
window7环境启动报onnxruntime.dll can not find，这个dll需要怎么安装？

**Comment by beyond-zj** [comment]
换ubuntu可以了

**Comment by moyangzhan** [comment]
onnxruntime.dll这个文件在onnxruntime.jar，如果win7找不到的话，可以先检查下maven的本地仓库有没有下载到这个包
