### ISSUE TITLE
hello,do u have some docs about this project?

### ISSUE THREAD

**Issue by jscksy** [moyangzhan/langchain4j-aideepin#23]
i'm a starter in llm application development, i want to have a systematic study about ur project. Would u like to provide some docs about tihs project? thank u very much!

**Comment by moyangzhan** [comment]
这个月还是以功能开发为主，主要功能的操作及相关设计文档打算放到下个月补充上去~

**Comment by jscksy** [comment]
> 这个月还是以功能开发为主，主要功能的操作及相关设计文档打算放到下个月补充上去~

好的谢谢，请问您是已经工作了还是在上学呀？

**Comment by moyangzhan** [comment]
> > 这个月还是以功能开发为主，主要功能的操作及相关设计文档打算放到下个月补充上去~
> 
> 好的谢谢，请问您是已经工作了还是在上学呀？

你这问题让我对自己的代码质量产生了深深的怀疑~~
github貌似没有私信的功能，有非项目相关的问题可以到gitee上私信我，这项目我也放到了gitee上，你能找得到的
