### ISSUE TITLE
访问ollama不可以呢？

### ISSUE THREAD

**Issue by GlanceQwQ** [moyangzhan/langchain4j-aideepin#25]
为什么不能访问ollama部署好的项目呢？
![ollama](https://github.com/moyangzhan/langchain4j-aideepin/assets/66995666/926c73ab-5bf6-4272-a2bf-deadb1d9d3b8)

**Comment by moyangzhan** [comment]
直接访问ollama是没问题的吗? 根据错误信息，ollama没有内容返回

**Comment by GlanceQwQ** [comment]
> 直接访问ollama是没问题的吗? 根据错误信息，ollama没有内容返回

作者您好，如果我想把上传的文档的知识点向量更加细节，应该怎么做？
