### ISSUE TITLE
关于RAG实现

### ISSUE THREAD

**Issue by mesxie** [moyangzhan/langchain4j-aideepin#3]
我可以基于该项目结合本地模型（例如ollama），将向量数据提供给模型作为知识使用吗。 而不是使用openkey调用在线的模型问答

**Comment by moyangzhan** [comment]
可以的，其实有打算接入本地模型，这个已经在计划之中了

**Comment by moyangzhan** [comment]
@mesxie ollama已经加上去了，版本：2.3.0
