### ISSUE TITLE
无法启动后端，求指点！

### ISSUE THREAD

**Issue by ChaseAfterLight** [moyangzhan/langchain4j-aideepin#31]
错误栈：
SLF4J: Class path contains multiple SLF4J providers.
SLF4J: Found provider [ch.qos.logback.classic.spi.LogbackServiceProvider@55040f2f]
SLF4J: Found provider [org.slf4j.simple.SimpleServiceProvider@64c87930]
SLF4J: See https://www.slf4j.org/codes.html#multiple_bindings for an explanation.
20:12:53,777 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.4.6
20:12:53,796 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
20:12:53,796 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/D:/3.AILearning/%e6%af%94%e8%b5%9b%e4%bb%a3%e7%a0%81/langchain4j-aideepin/adi-bootstrap/target/classes/logback.xml]
20:12:53,857 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word clr with class [org.springframework.boot.logging.logback.ColorConverter]
20:12:53,857 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word wex with class [org.springframework.boot.logging.logback.WhitespaceThrowableProxyConverter]
20:12:53,857 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word wEx with class [org.springframework.boot.logging.logback.ExtendedWhitespaceThrowableProxyConverter]
20:12:53,900 |-WARN in ch.qos.logback.core.model.processor.ImplicitModelHandler - Ignoring unknown property [springProperty] in [ch.qos.logback.classic.LoggerContext]
20:12:53,900 |-WARN in ch.qos.logback.core.model.processor.ImplicitModelHandler - Ignoring unknown property [springProperty] in [ch.qos.logback.classic.LoggerContext]
20:12:53,900 |-WARN in ch.qos.logback.core.model.processor.ImplicitModelHandler - Ignoring unknown property [springProperty] in [ch.qos.logback.classic.LoggerContext]
20:12:53,906 |-WARN in ch.qos.logback.core.model.processor.ImplicitModelHandler - Ignoring unknown property [springProfile] in [ch.qos.logback.classic.LoggerContext]
20:12:53,906 |-WARN in ch.qos.logback.core.model.processor.ImplicitModelHandler - Ignoring unknown property [springProfile] in [ch.qos.logback.classic.LoggerContext]
20:12:53,908 |-WARN in ch.qos.logback.core.model.processor.AppenderModelHandler - Appender named [StdoutAppender] not referenced. Skipping further processing.
20:12:53,908 |-WARN in ch.qos.logback.core.model.processor.AppenderModelHandler - Appender named [FileAppender] not referenced. Skipping further processing.
20:12:53,908 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@2beee7ff - End of configuration.
20:12:53,908 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@5136d012 - Registering current configuration as safe fallback point

SLF4J: Actual provider is of type [ch.qos.logback.classic.spi.LogbackServiceProvider@55040f2f]

Process finished with exit code 1
`

**Comment by moyangzhan** [comment]
错误堆栈就这么多吗？看起来信息好少~~
