### ISSUE TITLE
发送对话提示：conversation uuid error

### ISSUE THREAD

**Issue by alongken2005** [moyangzhan/langchain4j-aideepin#33]
请求体中conversationUuid的格式有问题，与正则不匹配导致
String uuidRegex = "^[0-9a-fA-F]{8}[0-9a-fA-F]{4}4[0-9a-fA-F]{3}[89abAB][0-9a-fA-F]{3}[0-9a-fA-F]{12}$";
        //check conversation uuid
        boolean isValid = Pattern.matches(uuidRegex, value.getConversationUuid());
：{"prompt":"ddd","conversationUuid":"default","regenerateQuestionUuid":"","modelName":"gpt-3.5-turbo"}

**Comment by moyangzhan** [comment]
是不是直接在表里创建了一个用户？正常情况下用户激活后会自动生成一个默认的会话，该会话的uuid是普通的uuid，而不是“default”，可以手工新建一个会话，刷新下就可以正常使用了
