### ISSUE TITLE
为什么无法连接1087端口呢，要怎么启动1087服务呢

### ISSUE THREAD

**Issue by Linzy0** [moyangzhan/langchain4j-aideepin#37]
![image](https://github.com/user-attachments/assets/01d9cbe7-202f-4dd0-9231-e23d19387300)

![image](https://github.com/user-attachments/assets/e6f3146a-fe04-45f1-861a-146c72b16e13)

**Comment by moyangzhan** [comment]
@Linzy0 127.0.0.1:1087是代理的地址，如果没有代理的话在application-dev.yml里把openai.proxy.enable设置为false就行了，不过这样的话就只能用千帆或文心一言了

**Comment by Linzy0** [comment]
聊天能正常响应，但是知识库问答报错了，请问是哪里出错了呢
![image](https://github.com/user-attachments/assets/8829dd31-f7e9-4ce0-bca8-197109f8a352)
![image](https://github.com/user-attachments/assets/7586f27e-6638-4f93-99a5-07ac5931cd59)
![image](https://github.com/user-attachments/assets/5d8c2644-c86f-496d-96e3-f1446c9c3289)
![image](https://github.com/user-attachments/assets/b7bad954-e0e3-43ea-924f-59cea62d445b)
![image](https://github.com/user-attachments/assets/b6e550d2-6dbe-44e3-8e52-54f34959cc7b)

**Comment by Linzy0** [comment]
@moyangzhan 你好，我想问一下AI直接提问是正常的，但知识库提问老是报错 java.lang.IllegalArgumentException: text cannot be null ，这时候应该怎么解决呢
