### ISSUE TITLE
画图-修图-上传文件出错401

### ISSUE THREAD

**Issue by nemolig** [moyangzhan/langchain4j-aideepin#39]
![image](https://github.com/user-attachments/assets/56c44bca-f40b-4454-b4db-a9d863f2703e)
![image](https://github.com/user-attachments/assets/b10ecaf7-a512-4846-a7b4-0966faafd8aa)

**Comment by moyangzhan** [comment]
@nemolig 重新拉一下前端代码就可以了，示例站也更新了
