### ISSUE TITLE
如果支持图片或者文档解析更好了

### ISSUE THREAD

**Issue by Hwongyohong** [moyangzhan/langchain4j-aideepin#4]
现在API都支持图片或者文档解析，作者下一步是否有这个想法

**Comment by moyangzhan** [comment]
如果我理解没错的话，你指的是如果大语言模型支持图片或文档输入，aideepin最好也支持这种输入？比如说通义千问支持图片的上传及解析，那在aideepin中选择通义千问时也提供相应的图片输入功能？
如果是这样的话，那这个功能值得考虑，不过优先级会比较低，近期不太可能有时间加上去了~~

**Comment by moyangzhan** [comment]
@flashback712 hello，目前知识库那块的功能就是RAG来的

**Comment by novembersky** [comment]
界面的问答好像默认不走知识库，走的ConversationMessageController，支持知识库的问答是单独入口KnowledgeBaseQAController，是还没集成在一起？

**Comment by novembersky** [comment]
试用和简略走读了一下，小而美的项目，赞一个。本来想加个chatglm的适配，发现langchain4j没有chatglm的流式实现.....

**Comment by moyangzhan** [comment]
> 试用和简略走读了一下，小而美的项目，赞一个。本来想加个chatglm的适配，发现langchain4j没有chatglm的流式实现.....

thx，欢迎提MR、多交流

**Comment by missawang** [comment]
nice，作者这个非常棒，如果加一个 模型管理的后台 那是非常好的，本地管理模型以及后台配置模型，我相信会更好，比如 ollam 、openai 改成 可改的 还有可以针对 ollma   实现命令管理 那也是非常不错的

**Comment by moyangzhan** [comment]
> nice，作者这个非常棒，如果加一个 模型管理的后台 那是非常好的，本地管理模型以及后台配置模型，我相信会更好，比如 ollam 、openai 改成 可改的 还有可以针对 ollma 实现命令管理 那也是非常不错的

目前是没精力做管理后台的，管理后台相关的功能暂时只能通过直接执行SQL脚本来代替，不过是有打算把模型的相关信息放到一张表，后续业务逻辑根据模型的不同信息来做不同的处理，比如说知识库对文本的截断，可以根据嵌入模型支持的最大token数量来决定一性可以截取多少。
