### ISSUE TITLE
谷歌搜索引擎报错

### ISSUE THREAD

**Issue by Linzy0** [moyangzhan/langchain4j-aideepin#40]
使用谷歌搜索引擎报错,数据库已经修改apikey和cx。
![image](https://github.com/user-attachments/assets/663bd03f-bbe4-4aef-8fce-eea82183ca82)
![image](https://github.com/user-attachments/assets/2a4ac5de-137e-4002-989f-23364d7ad8a6)
谷歌引擎apikey和cx能成功搜索信息
![image](https://github.com/user-attachments/assets/4ddf780e-8d1b-4a19-abd5-622c28feb459)

**Comment by moyangzhan** [comment]
国内没有使用代码应该是访问不了googleapis.com的，是不是只在浏览器设置了代理
