### ISSUE TITLE
知识库回答内容缺漏

### ISSUE THREAD

**Issue by Linzy0** [moyangzhan/langchain4j-aideepin#41]
知识库响应内容和显示内容不一致，响应内容是完整的，但是在解析渲染响应内容时只读取data第一行的内容
![image](https://github.com/user-attachments/assets/4743d8bd-4f8c-44a3-91b6-bf290915b184)
![image](https://github.com/user-attachments/assets/b303ebbd-8dfa-4ece-ab53-940e15a3a3ee)

**Comment by moyangzhan** [comment]
@Linzy0 最近在忙着搞graphRAG，没怎么有空看issue，有没有拉最新代码？前端及后端都要最新的，我记得之前是有修过类似的bug，包括千帆和灵积的模型响应结果渲染错乱的问题
