### ISSUE TITLE
sql 文件未更新？

### ISSUE THREAD

**Issue by EvaiGG** [moyangzhan/langchain4j-aideepin#43]
sql 文件里面没有看到ag_graph 表啊

Caused by: org.postgresql.util.PSQLException: ERROR: relation "ag_graph" does not exist
  位置：15

**Comment by moyangzhan** [comment]
是不是还没有安装Apache AGE？

**Comment by EvaiGG** [comment]
哦哦 库里没有安装 试了下 create extension age ， 表生成在了另外一个模式ag_catelog 下
