### ISSUE TITLE
聊天页有BUG

### ISSUE THREAD

**Issue by Hwongyohong** [moyangzhan/langchain4j-aideepin#6]
（1）创建new chat时新建的new chat会自动消失，需要重新点击
（2）当创建出来的new chat后，再点其他的聊天，新的会消失
（3）打开页面后，点击非首个聊天，会自动弹到第一个，需要重新点击其他聊天才能正常

**Comment by moyangzhan** [comment]
确实是有这些问题，明天会更新一个版本来解决~

**Comment by moyangzhan** [comment]
@Hwongyohong 已经修复，见2.5.0
