### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by Hwongyohong** [moyangzhan/langchain4j-aideepin#7]
作者你线上环境是用nginx吗？跨域怎么配置的，需要修改哪些地方？我打包前端后除了登录方法其他失效了，是否可以贴一下配置信息

**Comment by moyangzhan** [comment]
@Hwongyohong 是的，生产环境用的是nginx，做为WEB服务器及后端服务的反向代理服务器，配置用的是这个：
https://github.com/moyangzhan/langchain4j-aideepin-web/blob/main/docker-compose/nginx/nginx.conf

如果后端服务跟前端代码不是同一个服务器的话，改一下nginx.conf的这里就行了
	
```
location /api/ {   
  proxy_set_header X-Real-IP $remote_addr; #转发用户IP
  proxy_pass http://后端服务IP:PORT/;
}
```
