### ISSUE TITLE
注册账号时邮件激活问题

### ISSUE THREAD

**Issue by SakuraAug** [moyangzhan/langchain4j-aideepin#9]
复现项目时在网站上注册账号，可以收到激活邮件，但是网站拒绝链接，请问是什么原因？
![01](https://github.com/moyangzhan/langchain4j-aideepin/assets/128482439/0fb5fcf5-7d39-4c16-9d8d-4736514d217d)

![02](https://github.com/moyangzhan/langchain4j-aideepin/assets/128482439/2cb52b9f-0731-4b26-b757-eae5bf53f059)

**Comment by moyangzhan** [comment]
http://10.67.6.133:1002/是可以访问的吗？看起来不像是激活链接的问题，是这个ip地址不可用

**Comment by SakuraAug** [comment]
这个是当时连接无线网络时用的ip地址，没对dev.yml文件中的adi配置改动时，激活邮件的链接为http://localhost:1002/，也是拒绝访问的
![image](https://github.com/moyangzhan/langchain4j-aideepin/assets/128482439/8420fb7e-8348-48fa-b20a-3c49b1a081cd)

**Comment by moyangzhan** [comment]
你是本地开发时出现的问题，还是部署到服务器中出现的问题？

如果是部署到服务器中，那端口就不是1002了，应该是80或者443
